install hcp cli

diff --git a/h-bench b/h-bench
--- a/h-bench
+++ b/h-bench
@@ -4,6 +4,7 @@
 
 # set scrict mode
 # set -Eeuo pipefail
+set -o pipefail
 # some global constants
 cluster_name=$(echo $RANDOM | md5sum | head -c 10)      # random string as default cluster name
 prog="${0##*/}"                                         # program name
@@ -514,6 +515,19 @@ log_creation_phase() {
     echo "timing phase array: ${timing_phase[@]}"
 }
 
+install_hcp_cli() {
+    echo "downloading hcp cli..."
+    cli_url=$(oc get ConsoleCLIDownload hcp-cli-download -o json | jq -r '.spec.links[] | select(.text | test("Linux for x86_64")).href')
+    curl -k --output /tmp/hcp.tar.gz ${cli_url}
+    echo "extracting hcp binary to /usr/local/bin"
+    tar -xvf /tmp/hcp.tar.gz -C /usr/local/bin
+    HCP=$(command -v hcp)
+    if [[ -z "$HCP" ]]; then
+        die "failed to install hcp cli"
+    else
+        echo "hcp cli is installed successfully"
+    fi
+}
 #-- configuration --------------------------------------------------------------
 # create a config file if none exists
 if [[ ! -e "$conf_file" ]]; then
@@ -547,7 +561,8 @@ source "$conf_file"
 
 #-- Top Level -----------------------------------------------------------------
 if [[ -z "$HS" ]] && [[ -z "$HCP" ]]; then
-    die "hypershift or hcp cli is not installed"
+    echo "hcp cli is not installed"
+    install_hcp_cli
 fi
 
 if [[ -z "$BC" ]]; then
